kind: Template
apiVersion: v1
metadata:
  name: nitrate-deploy-template
objects:
- apiVersion: "v1"
  kind: "PersistentVolumeClaim"
  metadata:
    name: ${APP_NAME}-httpd-logs
  spec:
    accessModes:
      - "ReadWriteOnce"
    resources:
      requests:
        storage: ${HTTPD_LOGS_VOL_SIZE}
    volumeName: "pv0001"
#- apiVersion: "v1"
#  kind: "PersistentVolumeClaim"
#  metadata:
#    name: ${APP_NAME}-db-data
#  spec:
#    accessModes:
#    - "ReadWriteOnce"
#    resources:
#      requests:
#        storage: ${DB_VOL_SIZE}
#    volumeName: "pv0001"
- kind: "DeploymentConfig"
  apiVersion: "v1"
  metadata:
    name: ${APP_NAME}
  spec:
    template: 
      metadata:
        labels:
          name: ${APP_NAME}
      spec:
        containers:
        - name: "nitrate"
          image: ${WEB_APP_IMAGE}
          ports:
          - containerPort: 80
            protocol: "TCP"
          # volumeMounts:
          # - mountPath: ${HTTPD_LOGS_MOUNT_PATH}
          #   name: httpd-logs
#          - mountPath: ${DB_MOUNT_PATH}
#            name: db
          env:
          - name: NITRATE_SECRET_KEY
            value: nitrate_run_20210514
          - name: NITRATE_DB_ENGINE
            value: ${NITRATE_DB_ENGINE}
          - name: NITRATE_DB_NAME
            value: ${NITRATE_DB_NAME}
          - name: NITRATE_DB_HOST
            value: ${NITRATE_DB_HOST}
          - name: NITRATE_DB_USER
            value: ${NITRATE_DB_USER}
          - name: NITRATE_DB_PASSWORD
            value: ${NITRATE_DB_PASSWORD}
        # volumes:
        # - name: "httpd-logs"
        #   persistentVolumeClaim:
        #     claimName: ${APP_NAME}-httpd-logs
#        - name: "db"
#          persistentVolumeClaim:
#            claimName: ${APP_NAME}-db-data
    replicas: 1
    triggers:
    - type: "ConfigChange" 
- apiVersion: v1
  kind: Service
  metadata:
    name: ${APP_NAME}
  spec:
    selector:
      name: ${APP_NAME}
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
- apiVersion: v1
  kind: Route
  metadata:
    name: ${APP_NAME}
  spec:
    path: /tcms
    to:
      kind: Service
      name: ${APP_NAME}
parameters:
- description: The name of the Nitrate Web application used to name related objects.
  displayName: Application Name
  name: APP_NAME
  required: true
  value: nitrate-webapp
#- description: Storage size of database
#  name: DB_VOL_SIZE
#  required: true
#  value: 100Mi
- description: Storage size of httpd logs
  name: HTTPD_LOGS_VOL_SIZE
  required: true
  value: 50Mi
- description: Nitrate Web application container image
  name: WEB_APP_IMAGE
  required: true
  value: quay.io/nitrate/nitrate:latest
- description: Database engine
  name: NITRATE_DB_ENGINE
  required: true
  value: sqlite
- description: Database name
  name: NITRATE_DB_NAME
  required: true
  value: /var/nitrate.db
- description: Database host
  name: NITRATE_DB_HOST
  required: false
  value:
- description: Username used to log into database
  name: NITRATE_DB_USER
  required: false
  value:
- description: Password used to log into database
  name: NITRATE_DB_PASSWORD
  required: false
  value:
- description: httpd logs volume mount path
  name: HTTPD_LOGS_MOUNT_PATH
  required: true
  value: /var/log/httpd/
#- description: Database volume mount path
#  name: DB_MOUNT_PATH
#  required: true
#  value: /var/nitrate-db/
