kind: Template
apiVersion: v1
metadata:
  name: run-httpd
objects:
- kind: ImageStream
  apiVersion: v1
  metadata:
    name: run-httpd
- kind: BuildConfig
  apiVersion: v1
  metadata:
    name: run-httpd
  spec:
    source:
      git:
        uri: "https://github.com/tkdchen/play-oc"
        ref: "master"
    strategy:
      dockerStrategy:
        dockerfilePath: Dockerfile-run-httpd
    output: 
      to:
        kind: ImageStreamTag
        name: 172.30.1.1:5000/run-httpd/run-httpd:latest
- kind: DeploymentConfig
  apiVersion: v1
  metadata:
    name: run-httpd
  spec:
    template: 
      metadata:
        labels:
          name: run-httpd
      spec:
        containers:
        - name: mysite
          image: 172.30.1.1:5000/run-httpd/run-httpd:latest
          ports:
          - containerPort: 80
            protocol: "TCP"
    replicas: 1
    triggers:
    - type: "ConfigChange"
    - type: ImageChange
      imageChangeParams:
        automatic: true 
        from:
          kind: ImageStreamTag
          name: run-httpd:latest
        containerNames:
        - run-httpd
